config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"

  resources :restaurants, except: [:destroy] do
    collection do
      get :top
      get :bottom
    end

    member do
      get :chef       #  "get/restaurants/:id/chef"
    end

    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  CATEGORIES = %w(chinese italian japanese french belgian)
  validates :category, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, numericality: { only_integer: true, in: 0..5 }
  validates :rating, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review submitted'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

   <body>
    <%= render 'shared/navbar' %>
    <div class="container py-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.htlm.erb
<!-- <%#= form_with @restaurant do |f| %>
  <div class="form-group">
    <%#= f.label :name %>
    <%#= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%#= f.label :address %>
    <%#= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%#= f.label :category %>
    <%#= f.select :category, collection: Restaurant::CATEGORIES, class: "form-control" %>
  </div>
  <div class="form-group">
    <%#= f.label :phone_number %>
    <%#= f.date_field :phone_number, class: "form-control" %>
  </div>
  <div class="form-group">
    <%#= f.submit class: "btn btn-primary" %>
  </div>
<%# end %> -->

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant::CATEGORIES %>
  <%= f.input :phone_number %>
  <%= f.submit class: "btn btn-primary mt-4" %>
  <%#= link_to "Delete", restaurant_path(Restaurant.last), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" } %>
  <%#= button_to "Delete", restaurant_path(Restaurant.last), method: :delete, form: { data: { turbo_confirm: "Are your sure?" } } %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container mt-5">
  <h1>All restaurants</h1>

  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
  </ul>

  <%= link_to "Add a restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h1>Add a new restaurant</h1>

  <%= render "form" %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-5">
  <h1><%= @restaurant.name %> <small>(<%= @restaurant.species %>)</small></h1>
  <ul>
    <li>Address: <%= @restaurant.address %></li>
    <li>Category: <%= @restaurant.category %></li>
    <li>Phone number: <%= @restaurant.phone_number %></li>
  </ul>

  <%= link_to "Edit #{@restaurant.name}", edit_restaurant_path(@restaurant) %>
  <br>
  <%= link_to "Delete #{@restaurant.name}", restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" } %>
  <br>
  <%= link_to "Back to all restaurants", restaurants_path %>
</div>

app/views/reviews/new.html.erb
<h1>New review for <%= @restaurant.name %></h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>